x={"apple","orange","grapes","blue"}
print(x)
print(type(x))
x.add("lemon")
print(x)
y={"carrot","blue","cauli"}
print(y)
'''x.update(y)
print(x)'''
a=x.union(y)
print(a)
b=x.intersection(y)
print(b)
z={"janu","vini","mini"}
print(z)
v={"lallu","vini","mallu"}
print(v)
f=z.union(v)
print(f)
j=z.difference(v)
print(j)